export const CATEGORIES = [
  {
    id: 'about_you',
    title: 'Sobre você',
    description: 'Quem você é no dia a dia.',
    emoji: '🪞',
  },
  {
    id: 'personality',
    title: 'Personalidade',
    description: 'Como você pensa, sente e reage.',
    emoji: '🧠',
  },
  {
    id: 'hobbies',
    title: 'Hobbies',
    description: 'O que você curte fazer e consumir.',
    emoji: '🎯',
  },
  {
    id: 'family',
    title: 'Família',
    description: 'Laços, influências e proximidade.',
    emoji: '👨‍👩‍👧',
  },
  {
    id: 'friends',
    title: 'Amigos',
    description: 'Amizades e convivência social.',
    emoji: '🤝',
  },
  {
    id: 'relationship',
    title: 'Relacionamento',
    description: 'Romance, parceria e vínculo afetivo.',
    emoji: '💕',
  },
  {
    id: 'jealousy',
    title: 'Ciúmes',
    description: 'Limites, confiança e inseguranças.',
    emoji: '💭',
  },
  {
    id: 'communication',
    title: 'Comunicação',
    description: 'Como vocês conversam e resolvem conflitos.',
    emoji: '🗣️',
  },
  {
    id: 'money',
    title: 'Dinheiro',
    description: 'Finanças, hábitos e objetivos.',
    emoji: '💰',
  },
  {
    id: 'career',
    title: 'Carreira',
    description: 'Trabalho, ambição e prioridades.',
    emoji: '💼',
  },
  {
    id: 'future',
    title: 'Futuro',
    description: 'Planos, sonhos e visão de vida.',
    emoji: '🔮',
  },
  {
    id: 'marriage',
    title: 'Casamento',
    description: 'Compromisso, cerimônia e expectativas.',
    emoji: '💍',
  },
  {
    id: 'children',
    title: 'Filhos',
    description: 'Maternidade, paternidade e educação.',
    emoji: '👶',
  },
  {
    id: 'home_routine',
    title: 'Casa e rotina',
    description: 'Lar, tarefas e dia a dia.',
    emoji: '🏠',
  },
  {
    id: 'health',
    title: 'Saúde',
    description: 'Corpo, hábitos e bem-estar.',
    emoji: '🩺',
  },
  {
    id: 'spirituality',
    title: 'Espiritualidade',
    description: 'Fé, crenças e valores espirituais.',
    emoji: '🕯️',
  },
  {
    id: 'social_media',
    title: 'Redes sociais',
    description: 'Vida online e exposição pública.',
    emoji: '📱',
  },
  {
    id: 'values',
    title: 'Valores',
    description: 'O que é inegociável para você.',
    emoji: '⚖️',
  },
  {
    id: 'hypotheticals',
    title: 'Hipóteses',
    description: 'Cenários imaginários para puxar assunto.',
    emoji: '✨',
  },
  {
    id: 'about_us',
    title: 'Sobre nós',
    description: 'A dupla de vocês — memórias e impressões.',
    emoji: '👥',
  },
  {
    id: 'us_general',
    title: 'Nossa dupla',
    description: 'Dinâmica de vocês, sem assumir romance.',
    emoji: '🔗',
  },
  {
    id: 'us_friends',
    title: 'Nossa amizade',
    description: 'O que vocês dois compartilham como amigos.',
    emoji: '🫂',
  },
  {
    id: 'us_coworkers',
    title: 'No trabalho',
    description: 'Parceria profissional e rotina de equipe.',
    emoji: '🏢',
  },
  {
    id: 'us_roommates',
    title: 'Morando juntos',
    description: 'Casa, convivência e rotina compartilhada.',
    emoji: '🛋️',
  },
  {
    id: 'us_siblings',
    title: 'Entre irmãos',
    description: 'História, diferenças e laço fraternal.',
    emoji: '👫',
  },
  {
    id: 'us_parent_child',
    title: 'Pais e filhos',
    description: 'Vínculo entre gerações.',
    emoji: '🧑‍🧒',
  },
  {
    id: 'us_neighbors',
    title: 'Vizinhança',
    description: 'Convivência no bairro e no prédio.',
    emoji: '🏘️',
  },
  {
    id: 'us_classmates',
    title: 'Colegas de turma',
    description: 'Escola, faculdade e vida acadêmica.',
    emoji: '🎓',
  },
  {
    id: 'us_teammates',
    title: 'Time e grupo',
    description: 'Esporte, projeto ou grupo fechado.',
    emoji: '⚽',
  },
  {
    id: 'us_romantic',
    title: 'Romance',
    description: 'Vínculo afetivo e expectativas a dois.',
    emoji: '❤️',
  },
  // Legado — sessões antigas podem usar estas categorias
  {
    id: 'light',
    title: 'Leve',
    description: 'Para quebrar o gelo com naturalidade.',
    emoji: '☀️',
  },
  {
    id: 'deep',
    title: 'Profundo',
    description: 'Para ir além do superficial.',
    emoji: '🌊',
  },
  {
    id: 'fun',
    title: 'Divertido',
    description: 'Para rir e se surpreender juntos.',
    emoji: '🎲',
  },
];

export function categoryById(id) {
  return CATEGORIES.find((item) => item.id === id);
}
