const YND = ['Sim', 'Não', 'Depende'];
const yn = (text) => ({ text, type: 'SINGLE_CHOICE', options: YND });

export default [
  'O que você acha que eu não sei sobre você e deveria saber?',
  'Qual momento nosso você guarda com mais carinho?',
  'O que te faz sentir que somos uma boa dupla?',
  'Em que situação você se sente mais conectado(a) comigo?',
  'O que você gostaria que eu entendesse melhor sobre você?',
  'Qual hábito meu te faz sorrir?',
  'O que você admira em mim que raramente diz?',
  yn('Você se sente à vontade sendo vulnerável comigo?'),
  'Qual memória nossa você contaria para um amigo?',
  'O que te faz sentir que estamos evoluindo juntos?',
  'Qual gesto meu te faz sentir amado(a)?',
  'O que você gostaria que fizéssemos mais vezes?',
  'Em que momento você se sentiu mais orgulhoso(a) de nós?',
  yn('Você se imagina envelhecendo ao meu lado?'),
  'O que te faz sentir que posso confiar em mim?',
  'Qual conversa nossa te marcou profundamente?',
  'O que você gostaria de experimentar comigo?',
  'Em que aspecto você acha que nos complementamos?',
  'O que te faz sentir que sou a pessoa certa para você?',
  yn('Você se sente ouvido(a) quando fala comigo?'),
  'Qual tradição você gostaria de criar só nossa?',
  'O que te faz sentir que superamos bem os desafios?',
  'Qual qualidade minha te inspira?',
  'O que você gostaria que eu soubesse sobre como te amo?',
  'Em que momento você soube que queria algo sério comigo?',
  yn('Você se sente respeitado(a) por mim?'),
  'Qual plano futuro nosso te empolga mais?',
  'O que te faz sentir que nossa conexão é especial?',
  'Qual elogio meu você mais gostou de receber?',
  'O que você faria diferente na nossa relação se pudesse voltar?',
];
