const YND = ['Sim', 'Não', 'Depende'];
const yn = (text) => ({ text, type: 'SINGLE_CHOICE', options: YND });

export default [
  'Qual apelido de infância você ainda carrega com carinho?',
  'O que você faz quando precisa se reconectar consigo mesmo(a)?',
  'Qual parte da sua personalidade demora mais para as pessoas conhecerem?',
  'O que te faz sentir orgulho de quem você se tornou?',
  'Qual hábito seu as pessoas mais estranham?',
  yn('Você se considera uma pessoa autêntica no dia a dia?'),
  'O que você faria se tivesse um dia inteiro só para você?',
  'Qual elogio você acha difícil de aceitar?',
  'O que te deixa vulnerável de um jeito bom?',
  'Qual versão sua — criança, adolescente ou adulto(a) — você mais gostaria de reencontrar?',
  yn('Você costuma se comparar com outras pessoas?'),
  'O que você guarda no coração e raramente conta?',
  'Qual barulho, cheiro ou lugar te traz paz imediata?',
  'O que você aprendeu sobre si depois de uma fase difícil?',
  yn('Você se sente compreendido(a) pela maioria das pessoas?'),
  'Qual decisão pequena mudou sua vida sem você perceber na hora?',
  'O que você faz quando quer se sentir mais confiante?',
  'Qual parte do seu corpo ou aparência você aprendeu a aceitar?',
  yn('Você gosta de ficar sozinho(a)?'),
  'O que te faz rir sozinho(a)?',
  'Qual tradição pessoal você criou para si?',
  'O que você considera sua maior conquista que não aparece no currículo?',
  'Como você reage quando alguém te vê chorando?',
  yn('Você se descreve como otimista?'),
  'Qual música descreve um capítulo importante da sua vida?',
  'O que você faria diferente se pudesse voltar um ano?',
  'Qual medo você superou e como?',
  'O que te faz sentir pequeno(a) diante do mundo?',
  yn('Você costuma pedir ajuda quando precisa?'),
  'Qual qualidade sua você subestima?',
  'O que você faria se ninguém fosse julgar?',
  'Qual momento te fez perceber que estava crescendo?',
  yn('Você se sente à vontade sendo o centro das atenções?'),
  'O que você coleciona — literal ou simbolicamente?',
  'Qual conselho você daria para a versão adolescente de si?',
  'O que te faz sentir grato(a) hoje?',
  yn('Você guarda rancor por muito tempo?'),
  'Qual rotina te mantém equilibrado(a)?',
  'O que você admira em si que outras pessoas nem percebem?',
  'Qual situação te mostrou do que você é capaz?',
  yn('Você se considera uma pessoa curiosa?'),
  'O que você faria se tivesse coragem de arriscar mais?',
  'Qual memória você revisita quando precisa de força?',
  'O que te define além do trabalho e do relacionamento?',
  yn('Você se perdoa com facilidade?'),
  'Qual parte da sua história você gostaria que mais pessoas soubessem?',
  'O que te deixa emocionado(a) sem explicação lógica?',
  'Como você sabe que está no caminho certo?',
  yn('Você se sente em paz com quem é hoje?'),
  'O que você quer que as pessoas lembrem de você?',
];
