const YND = ['Sim', 'Não', 'Depende'];
const yn = (text) => ({ text, type: 'SINGLE_CHOICE', options: YND });

export default [
  'O que te motiva a levantar da cama para trabalhar?',
  yn('Você se sente realizado(a) na carreira atual?'),
  'Qual habilidade profissional você quer desenvolver?',
  yn('Você aceitaria redução de salário por mais qualidade de vida?'),
  'Como você lida com burnout?',
  yn('Você prefere emprego estável ou autonomia?'),
  'Qual foi o feedback profissional que mais te marcou?',
  yn('Você networking com frequência?'),
  'Como você lida com concorrência no trabalho?',
  yn('Você aceitaria promoção com mais responsabilidade?'),
  'Qual valor profissional é inegociável para você?',
  yn('Você trabalha no feriado se precisar?'),
  'Como você lida com chefes difíceis?',
  yn('Você prefere home office ou presencial?'),
  'Qual conquista profissional você ainda busca?',
  yn('Você aceitaria demissão por princípio?'),
  'Como você lida com falta de reconhecimento?',
  yn('Você tem side hustle ou projeto paralelo?'),
  'Qual ambiente de trabalho te faz render mais?',
  yn('Você aceitaria recontratação em empresa antiga?'),
  'Como você lida com mudanças de carreira?',
  yn('Você prefere especialização ou generalização?'),
  'Qual erro profissional te ensinou mais?',
  yn('Você aceitaria viagens frequentes a trabalho?'),
  'Como você lida com colegas que não puxam o peso?',
  yn('Você tem mentor ou referência profissional?'),
  'Qual meta de carreira você tem para os próximos três anos?',
  yn('Você aceitaria trabalhar no exterior?'),
  'Como você lida com desemprego?',
  yn('Você prefere empresa grande ou pequena?'),
  'Qual habilidade soft você mais valoriza?',
  yn('Você aceitaria cargo com menos visibilidade?'),
  'Como você lida com críticas no trabalho?',
  yn('Você tem plano B profissional?'),
  'Qual setor te atrai para uma mudança?',
  yn('Você aceitaria trabalhar aos fins de semana?'),
  'Como você lida com política interna?',
  yn('Você prefere liderar equipe ou trabalhar solo?'),
  'Qual projeto profissional você mais se orgulha?',
  yn('Você aceitaria estágio em nova área?'),
  'Como você lida com prazos apertados?',
  yn('Você tem portfólio ou currículo atualizado?'),
  'Qual benefício além do salário é essencial?',
  yn('Você aceitaria contrato PJ em vez de CLT?'),
  'Como você lida com falta de propósito no trabalho?',
  yn('Você prefere rotina ou variedade no trabalho?'),
  'Qual lição sobre carreira você aprendeu da pior forma?',
  yn('Você aceitaria mudar de cidade por emprego?'),
  'Como você equilibra ambição e bem-estar?',
  yn('Você se vê na mesma área daqui a dez anos?'),
];
