const YND = ['Sim', 'Não', 'Depende'];
const yn = (text) => ({ text, type: 'SINGLE_CHOICE', options: YND });

export default [
  yn('Você quer ser pai/mãe biológico(a)?'),
  'Como você imagina o quarto do primeiro filho?',
  yn('Você aceitaria ter filhos mais tarde na vida?'),
  'Qual tradição você quer passar para os filhos?',
  yn('Você aceitaria ter apenas um filho?'),
  'Como você lida com a ideia de noites mal dormidas?',
  yn('Você aceitaria escola pública ou privada?'),
  'Qual valor você ensinaria desde cedo?',
  yn('Você aceitaria ter filhos com diferença grande de idade?'),
  'Como você imagina as férias em família?',
  yn('Você aceitaria creche desde cedo?'),
  'Qual brincadeira da infância você quer repetir?',
  yn('Você aceitaria ter filhos gêmeos?'),
  'Como você lida com birras e limites?',
  yn('Você aceitaria ter filhos por adoção?'),
  'Qual hábito saudável você quer incutir?',
  yn('Você aceitaria ter filhos antes de casar?'),
  'Como você imagina a divisão de tarefas com filhos?',
  yn('Você aceitaria ter filhos se a carreira estivesse em ascensão?'),
  'Qual memória de infância você quer recriar?',
  yn('Você aceitaria ter filhos com necessidades especiais?'),
  'Como você lida com críticas sobre educação?',
  yn('Você aceitaria ter filhos em outro país?'),
  'Qual regra de casa você teria com filhos?',
  yn('Você aceitaria ter filhos se morasse longe da família?'),
  'Como você imagina ensinar sobre dinheiro?',
  yn('Você aceitaria ter filhos se o parceiro não quisesse?'),
  'Qual atividade você faria com os filhos?',
  yn('Você aceitaria ter filhos com ajuda de reprodução assistida?'),
  'Como você lida com comparação entre filhos?',
  yn('Você aceitaria ter filhos e pets juntos?'),
  'Qual limite você colocaria em telas?',
  yn('Você aceitaria ter filhos se a renda fosse instável?'),
  'Como você imagina o nascimento?',
  yn('Você aceitaria ter filhos se morasse em apartamento pequeno?'),
  'Qual tradição de aniversário você criaria?',
  yn('Você aceitaria ter filhos se um dos dois viajasse muito?'),
  'Como você lida com a pressão para ter filhos?',
  yn('Você aceitaria ter filhos se houvesse risco genético?'),
  'Qual conselho você daria para um filho adolescente?',
  yn('Você aceitaria ter filhos se morasse com os pais?'),
  'Como você imagina a relação avós-netos?',
  yn('Você aceitaria ter filhos se um dos dois tivesse filhos de relacionamento anterior?'),
  'Qual valor sobre respeito você ensinaria?',
  yn('Você aceitaria ter filhos se a saúde mental não estivesse estável?'),
  'Como você lida com a ideia de nunca ter filhos?',
  yn('Você aceitaria ter filhos se morasse longe da escola ideal?'),
  'O que te faria reconsiderar ter filhos?',
  yn('Você aceitaria ter filhos se morassem longe dos avós?'),
  'Como você imagina ensinar empatia desde cedo?',
];
