const YND = ['Sim', 'Não', 'Depende'];
const yn = (text) => ({ text, type: 'SINGLE_CHOICE', options: YND });

export default [
  'Como você prefere que a outra pessoa te avise quando está chateada?',
  yn('Você consegue dizer "não" com clareza?'),
  'O que te faz sentir que a conversa foi produtiva?',
  yn('Você prefere mensagens longas ou conversas rápidas?'),
  'Como você lida quando a outra pessoa não quer falar sobre algo?',
  yn('Você consegue admitir quando está errado(a)?'),
  'O que te faz sentir interrompido(a) ou não ouvido(a)?',
  yn('Você prefere resolver mal-entendidos por texto ou pessoalmente?'),
  'Como você reage quando a outra pessoa muda de assunto no meio da conversa?',
  yn('Você consegue falar sobre necessidades emocionais?'),
  'O que te ajuda a manter a calma numa discussão?',
  yn('Você prefere feedback direto ou suave?'),
  'Como você lida com silêncios desconfortáveis?',
  yn('Você consegue pedir desculpas sem justificar demais?'),
  'O que te faz sentir que a outra pessoa está presente na conversa?',
  yn('Você prefere combinar assuntos difíceis com antecedência?'),
  'Como você reage quando a outra pessoa levanta a voz?',
  yn('Você consegue expressar gratidão com facilidade?'),
  'O que te faz sentir que precisa de um tempo sozinho(a)?',
  yn('Você prefere resolver conflitos no mesmo dia?'),
  'Como você lida quando a outra pessoa não responde por horas?',
  yn('Você consegue falar sobre limites pessoais?'),
  'O que te faz sentir que a outra pessoa te entende?',
  yn('Você prefere conversas profundas ou leves no dia a dia?'),
  'Como você reage quando a outra pessoa faz suposições sobre você?',
  yn('Você consegue dizer quando precisa de espaço?'),
  'O que te faz sentir que uma conversa virou discussão?',
  yn('Você prefere receber críticas em particular?'),
  'Como você lida com diferenças de opinião firmes?',
  yn('Você consegue falar sobre expectativas?'),
  'O que te faz sentir que a outra pessoa está evitando o assunto?',
  yn('Você prefere combinar regras de convivência?'),
  'Como você reage quando a outra pessoa usa ironia?',
  yn('Você consegue falar sobre o que te magoa?'),
  'O que te faz sentir que precisa repetir algo várias vezes?',
  yn('Você prefere resolver conflitos com um mediador?'),
  'Como você lida quando a outra pessoa não lembra do que combinaram?',
  yn('Você consegue elogiar a outra pessoa com frequência?'),
  'O que te faz sentir que a comunicação está fluindo?',
  yn('Você prefere conversas matinais ou noturnas?'),
  'Como você reage quando a outra pessoa compartilha algo íntimo?',
  yn('Você consegue falar sobre planos futuros juntos?'),
  'O que te faz sentir que precisa de mais clareza?',
  yn('Você prefere resolver conflitos com humor?'),
  'Como você lida quando a outra pessoa não concorda com seu ponto de vista?',
  yn('Você consegue pedir ajuda quando precisa?'),
  'O que te faz sentir que a outra pessoa te respeita na conversa?',
  yn('Você consegue reconhecer quando a outra pessoa precisa de apoio?'),
  'Como você lida quando a outra pessoa interpreta mal suas palavras?',
  'O que te faz sentir que vale a pena insistir numa conversa difícil?',
];
