const YND = ['Sim', 'Não', 'Depende'];
const yn = (text) => ({ text, type: 'SINGLE_CHOICE', options: YND });

export default [
  'Qual parente você mais se parece em personalidade?',
  yn('Você mantém contato regular com parentes distantes?'),
  'Como sua família lida com conflitos?',
  yn('Reuniões familiares grandes te energizam ou cansam?'),
  'Qual tradição familiar você gostaria de criar no futuro?',
  'O que você aprendeu de errado e de certo com sua família?',
  yn('Você se sente responsável pelos problemas dos seus pais?'),
  'Como você equilibra família de origem e vida adulta?',
  'Qual memória de Natal ou Ano-Novo você mais guarda?',
  yn('Você conta tudo para sua família?'),
  'Como você lida com diferenças de opinião com parentes?',
  'Qual valor familiar você carrega para a vida?',
  yn('Você gostaria que seus filhos crescessem perto dos avós?'),
  'Como sua família reagiu às suas escolhas importantes?',
  'Qual parente te deu o melhor conselho?',
  yn('Você se sente pressionado(a) a seguir expectativas familiares?'),
  'Como você imagina envelhecer com sua família?',
  'Qual papel os irmãos ocupam na sua vida?',
  yn('Você perdoa erros dos pais com facilidade?'),
  'Como você lida com parentes difíceis?',
  'Qual receita ou comida da família você mais sente falta?',
  yn('Você participa de decisões importantes da família?'),
  'Como você mantém laços com família que mora longe?',
  'Qual história de família você gosta de contar?',
  yn('Você se sente compreendido(a) pela sua família?'),
  'Como você reage quando a família se mete na sua vida?',
  'Qual lição sobre amor você aprendeu em casa?',
  yn('Você gostaria de morar no mesmo bairro que algum parente?'),
  'Como você lida com comparações entre irmãos ou primos?',
  'Qual momento difícil uniu sua família?',
  yn('Você mantém fotos e lembranças de família em casa?'),
  'Como você honra quem já partiu na sua família?',
  'Qual expectativa familiar você quebrou?',
  yn('Você se sente culpado(a) por morar longe da família?'),
  'Como você introduz pessoas importantes para sua família?',
  'Qual hábito de família você quer abandonar?',
  yn('Você confia nos conselhos da sua família?'),
  'Como você lida com segredos de família?',
  'Qual parente você gostaria de conhecer melhor?',
  yn('Você participa de grupos de WhatsApp da família?'),
  'Como você reage quando parentes pedem favores financeiros?',
  'Qual tradição familiar você acha antiquada?',
  yn('Você se sente parte de uma comunidade além da família?'),
  'Como você lida com diferenças geracionais em casa?',
  'Qual sonho sua família tem para você?',
  yn('Você gostaria de registrar a história da sua família?'),
  'Como você define "família" para além do sangue?',
  yn('Você gostaria de reunir toda a família numa mesma cidade?'),
  'Qual parente você sente falta de ter conhecido melhor?',
  'Como você lida quando família e escolhas pessoais entram em conflito?',
];
