const YND = ['Sim', 'Não', 'Depende'];
const yn = (text) => ({ text, type: 'SINGLE_CHOICE', options: YND });

export default [
  'O que faz uma amizade durar décadas para você?',
  yn('Você faz amigos com facilidade?'),
  'Como você lida com amizades que ficaram distantes?',
  yn('Você acredita que amizade exige contato frequente?'),
  'Qual foi a maior lição que uma amizade te ensinou?',
  'Como você reage quando um amigo te decepciona?',
  yn('Você tem amigos de diferentes fases da vida?'),
  'O que você valoriza mais num amigo: lealdade, diversão ou honestidade?',
  'Como você lida com amizades tóxicas?',
  yn('Você se abre emocionalmente com amigos?'),
  'Qual programa ideal para passar um dia com amigos?',
  'Como você mantém amizades quando a rotina aperta?',
  yn('Você faz amizade com colegas de trabalho?'),
  'O que te faz sentir excluído(a) num grupo de amigos?',
  'Como você reage quando um amigo cancela em cima da hora?',
  yn('Você acredita em amizades de infância que duram para sempre?'),
  'Qual limite você coloca nas amizades?',
  'Como você celebra conquistas dos seus amigos?',
  yn('Você sente ciúmes de amizades dos seus amigos?'),
  'O que você faria se um amigo te pedisse um favor difícil?',
  'Como você lida com amigos que mudaram de personalidade?',
  yn('Você prefere amizades profundas ou muitas conhecidas?'),
  'Qual foi o melhor conselho que um amigo te deu?',
  'Como você reage quando amigos discordam de você publicamente?',
  yn('Você mantém amizade com pessoas de ideologias muito diferentes?'),
  'O que te faz sentir grato(a) por ter certos amigos?',
  'Como você lida com amigos que só aparecem quando precisam?',
  yn('Você organiza encontros ou espera ser convidado(a)?'),
  'Qual tradição você tem com seus amigos?',
  'Como você apoia um amigo em crise?',
  yn('Você conta segredos de amigos para outras pessoas?'),
  'O que te faz perder o interesse numa amizade?',
  'Como você lida com amigos que moram longe?',
  yn('Você se sente à vontade sendo você mesmo(a) com amigos?'),
  'Qual foi a viagem ou aventura mais marcante com amigos?',
  'Como você reage quando um amigo te critica com carinho?',
  yn('Você acredita que amizade pode sobreviver a longos períodos sem contato?'),
  'O que você faria se um amigo traísse sua confiança?',
  'Como você equilibra tempo para diferentes grupos de amigos?',
  yn('Você faz amizade com vizinhos?'),
  'Qual qualidade você mais admira nos seus amigos?',
  'Como você lida com amigos que se tornaram pais?',
  yn('Você se sente responsável pela felicidade dos seus amigos?'),
  'O que te faz sentir parte de um grupo?',
  'Como você reage quando amigos formam novos círculos sociais?',
  yn('Você guarda presentes e lembranças de amigos?'),
  'Qual foi a maior briga que você teve com um amigo e como resolveu?',
  'Como você lida com amizades onde há desequilíbrio de esforço?',
  yn('Você acredita que amizade verdadeira dispensa explicações?'),
  'O que você faria para reconquistar uma amizade perdida?',
];
