const YND = ['Sim', 'Não', 'Depende'];
const yn = (text) => ({ text, type: 'SINGLE_CHOICE', options: YND });

export default [
  'Como você imagina um sábado ideal daqui a três anos?',
  yn('Você tem um "bucket list" escrito?'),
  'Qual lugar do mundo você quer conhecer antes de morrer?',
  yn('Você planeja mudar de cidade nos próximos anos?'),
  'Como você define "vida boa"?',
  yn('Você se vê com filhos no futuro?'),
  'Qual meta pessoal você quer alcançar este ano?',
  yn('Você acredita que seus sonhos vão se realizar?'),
  'Como você imagina suas férias daqui a cinco anos?',
  yn('Você quer morar no interior ou na capital?'),
  'Qual hábito futuro você quer manter para sempre?',
  yn('Você se vê empreendendo no futuro?'),
  'Como você imagina seu aniversário daqui a dez anos?',
  yn('Você quer aprender um novo idioma?'),
  'Qual experiência você quer viver antes dos 50?',
  yn('Você se vê morando sozinho(a) em algum momento?'),
  'Como você imagina sua rotina de aposentadoria?',
  yn('Você quer escrever um livro ou criar algo duradouro?'),
  'Qual meta de saúde você quer alcançar?',
  yn('Você se vê viajando muito no futuro?'),
  'Como você imagina suas amizades daqui a vinte anos?',
  yn('Você quer ter pets no futuro?'),
  'Qual projeto pessoal você quer terminar?',
  yn('Você se vê morando perto do mar ou da montanha?'),
  'Como você imagina celebrar conquistas futuras?',
  yn('Você quer fazer voluntariado ou trabalho social?'),
  'Qual meta financeira de longo prazo você tem?',
  yn('Você se vê com rotina mais calma ou mais intensa?'),
  'Como você imagina seu lar ideal?',
  yn('Você quer aprender a tocar um instrumento?'),
  'Qual viagem em família você sonha em fazer?',
  yn('Você se vê mudando de país algum dia?'),
  'Como você imagina seu legado?',
  yn('Você quer ter um jardim ou horta?'),
  'Qual meta de aprendizado você tem?',
  yn('Você se vê com mais ou menos amigos no futuro?'),
  'Como você imagina suas manhãs daqui a dez anos?',
  yn('Você quer fazer uma pós ou especialização?'),
  'Qual meta de bem-estar você prioriza?',
  yn('Você se vê com rotina de exercícios fixa?'),
  'Como você imagina passar o Natal daqui a cinco anos?',
  yn('Você quer ter um negócio próprio?'),
  'Qual meta criativa você tem?',
  yn('Você se vê morando em casa própria?'),
  'Como você imagina envelhecer?',
  yn('Você quer aprender uma profissão nova?'),
  'Qual meta de relacionamento você tem para o futuro?',
  yn('Você se vê com mais tempo livre ou mais ocupado(a)?'),
  'Como você imagina comemorar a aposentadoria?',
  yn('Você se vê realizando um sonho de infância no futuro?'),
];
