const YND = ['Sim', 'Não', 'Depende'];
const yn = (text) => ({ text, type: 'SINGLE_CHOICE', options: YND });

export default [
  yn('Você faz check-up médico anualmente?'),
  'Qual hábito de saúde você quer adotar?',
  yn('Você toma vitaminas ou suplementos?'),
  'Como você lida com dor de cabeça?',
  yn('Você pratica meditação ou mindfulness?'),
  'Qual alimento você evita por saúde?',
  yn('Você tem alergias conhecidas?'),
  'Como você lida com insônia?',
  yn('Você bebe água suficiente no dia?'),
  'Qual exercício você mais gosta?',
  yn('Você evita açúcar ou processed foods?'),
  'Como você lida com ansiedade?',
  yn('Você usa óculos ou lentes?'),
  'Qual hábito ruim de saúde você quer abandonar?',
  yn('Você faz exames preventivos?'),
  'Como você lida com resfriados e gripes?',
  yn('Você tem plano de saúde?'),
  'Qual meta de saúde física você tem?',
  yn('Você evita álcool em excesso?'),
  'Como você lida com estresse crônico?',
  yn('Você tem histórico familiar de doenças?'),
  'Qual rotina de sono funciona para você?',
  yn('Você evita fumar ou tabaco?'),
  'Como você lida com dores musculares?',
  yn('Você faz alongamento ou yoga?'),
  'Qual hábito mental te faz bem?',
  yn('Você evita cafeína à noite?'),
  'Como você lida com falta de energia?',
  yn('Você tem restrição alimentar por saúde?'),
  'Qual meta de bem-estar emocional você tem?',
  yn('Você evita telas antes de dormir?'),
  'Como você lida com enxaquecas?',
  yn('Você tem rotina de skincare?'),
  'Qual hábito de saúde você mantém há anos?',
  yn('Você evita comer tarde da noite?'),
  'Como você lida com problemas digestivos?',
  yn('Você faz acompanhamento psicológico?'),
  'Qual meta de peso ou forma física você tem?',
  yn('Você evita sol excessivo?'),
  'Como você lida com dores nas costas?',
  yn('Você tem rotina de hidratação?'),
  'Qual hábito de saúde você aprendeu recentemente?',
  yn('Você evita automedicação?'),
  'Como você lida com falta de motivação para exercício?',
  yn('Você tem rotina de pausas no trabalho?'),
  'Qual meta de saúde mental você prioriza?',
  yn('Você evita junk food com frequência?'),
  'Como você lida com problemas de pele?',
  yn('Você tem rotina de gratidão ou journaling?'),
  'O que te faz sentir saudável de verdade?',
];
