const YND = ['Sim', 'Não', 'Depende'];
const yn = (text) => ({ text, type: 'SINGLE_CHOICE', options: YND });

export default [
  'Qual hobby você abandonou e gostaria de retomar?',
  yn('Você gosta de cozinhar por prazer?'),
  'Qual instrumento musical você gostaria de dominar?',
  yn('Você prefere ler ficção ou não ficção?'),
  'Qual jogo — videogame, tabuleiro ou cartas — te prende mais?',
  'Qual festival ou evento cultural você sonha em ir?',
  yn('Você gosta de acampar ou estar na natureza?'),
  'Qual doceria, prato ou receita você faz de olhos fechados?',
  yn('Você curte ir ao cinema sozinho(a)?'),
  'Qual podcast ou canal você recomendaria para qualquer um?',
  'Qual esporte você assiste mesmo sem praticar?',
  yn('Você gosta de dançar, mesmo sem saber?'),
  'Qual hobby você descobriu na pandemia ou numa fase recente?',
  'Qual lugar da cidade você leva visitantes para conhecer?',
  yn('Você prefere museus ou parques de diversão?'),
  'Qual série você reassistiria do zero?',
  'Qual comida de rua você nunca recusa?',
  yn('Você gosta de fotografar momentos do dia a dia?'),
  'Qual artista você gostaria de ver ao vivo?',
  'Qual brinquedo ou jogo da infância você ainda sente saudade?',
  yn('Você curte puzzles, palavras cruzadas ou jogos de lógica?'),
  'Qual viagem curta você faria num fim de semana?',
  'Qual hobby você pratica para desestressar?',
  yn('Você gosta de ir a shows e festivais?'),
  'Qual receita você quer aprender a fazer?',
  'Qual gênero musical você descobriu tarde e passou a amar?',
  yn('Você prefere maratonar séries ou assistir aos poucos?'),
  'Qual esporte radical você tentaria uma vez?',
  'Qual hobby você faz que poucos conhecem?',
  yn('Você gosta de ir a feiras, mercados ou brechós?'),
  'Qual filme você indica para quem quer te conhecer melhor?',
  'Qual atividade ao ar livre te recarrega?',
  yn('Você curte jogos online com outras pessoas?'),
  'Qual hobby você gostaria de compartilhar com alguém especial?',
  'Qual comida você cozinha quando quer impressionar?',
  yn('Você prefere teatro ou stand-up?'),
  'Qual livro você emprestaria com confiança?',
  'Qual trilha ou caminhada você repetiria?',
  yn('Você gosta de colecionar algo?'),
  'Qual hobby te ensinou algo sobre paciência?',
  'Qual lugar do Brasil você ainda quer conhecer?',
  yn('Você curte experimentar comidas de outros países?'),
  'Qual instrumento ou hobby artístico te atrai?',
  'Qual jogo de infância você ainda joga de vez em quando?',
  yn('Você gosta de ir a bibliotecas ou livrarias?'),
  'Qual hobby te conecta com outras pessoas?',
  'Qual filme de animação você nunca enjoa?',
  yn('Você prefere atividades calmas ou cheias de adrenalina?'),
  'Qual hobby você faria se tivesse mais tempo livre?',
  yn('Você gosta de aprender coisas novas por diversão?'),
];
