const YND = ['Sim', 'Não', 'Depende'];
const yn = (text) => ({ text, type: 'SINGLE_CHOICE', options: YND });

export default [
  yn('Você prefere acordar cedo ou dormir até tarde?'),
  'Como você imagina a cozinha ideal?',
  yn('Você gosta de plantas em casa?'),
  'Qual cheiro te faz sentir em casa?',
  yn('Você prefere casa minimalista ou cheia de objetos?'),
  'Como você lida com barulho dos vizinhos?',
  yn('Você gosta de ter música ambiente em casa?'),
  'Qual canto da casa é seu favorito?',
  yn('Você prefere jantar à mesa ou no sofá?'),
  'Como você imagina a sala de estar?',
  yn('Você gosta de ter visitas frequentes?'),
  'Qual rotina noturna te relaxa?',
  yn('Você prefere lavar louça na hora ou acumular?'),
  'Como você lida com sujeira de pets?',
  yn('Você gosta de ter velas ou incenso em casa?'),
  'Qual tarefa doméstica você faz com prazer?',
  yn('Você prefere varanda ou quintal?'),
  'Como você imagina o banheiro ideal?',
  yn('Você gosta de ter geladeira sempre cheia?'),
  'Qual hábito matinal é inegociável?',
  yn('Você prefere ar-condicionado ou ventilador?'),
  'Como você lida com bagunça temporária?',
  yn('Você gosta de ter quadros ou fotos na parede?'),
  'Qual comida de conforto você sempre tem em casa?',
  yn('Você prefere cozinha aberta ou separada?'),
  'Como você imagina o quarto ideal?',
  yn('Você gosta de ter livros espalhados?'),
  'Qual rotina de fim de semana em casa te agrada?',
  yn('Você prefere chuveiro ou banheira?'),
  'Como você lida com falta de espaço?',
  yn('Você gosta de ter TV no quarto?'),
  'Qual ambiente precisa estar sempre arrumado?',
  yn('Você prefere cortinas ou persianas?'),
  'Como você imagina a área de trabalho em casa?',
  yn('Você gosta de ter café da manhã elaborado?'),
  'Qual hábito noturno te prepara para dormir?',
  yn('Você prefere casa com muita luz natural?'),
  'Como você lida com temperatura em casa?',
  yn('Você gosta de ter flores frescas?'),
  'Qual rotina de limpeza funciona para você?',
  yn('Você prefere móveis novos ou antigos?'),
  'Como você imagina a garagem ou área externa?',
  yn('Você gosta de ter snacks sempre disponíveis?'),
  'Qual tradição doméstica você quer criar?',
  yn('Você prefere casa silenciosa ou com barulho de fundo?'),
  'Como você lida com organização de armários?',
  yn('Você gosta de cozinhar para visitas?'),
  'Qual detalhe torna um lar acolhedor para você?',
  yn('Você prefere morar perto ou longe do centro?'),
  'Como você imagina envelhecer no mesmo lar?',
];
