const YND = ['Sim', 'Não', 'Depende'];
const yn = (text) => ({ text, type: 'SINGLE_CHOICE', options: YND });

export default [
  'Se você pudesse trocar de vida com alguém por um dia, quem seria?',
  'Se acordasse com um superpoder, qual escolheria?',
  'Se pudesse apagar uma memória, qual seria?',
  'Se ganhasse uma viagem all-inclusive para qualquer lugar, para onde iria?',
  'Se pudesse jantar com três pessoas da história, quem convidaria?',
  yn('Se descobrisse que tem um mês de vida, contaria para todos?'),
  'Se pudesse dominar um idioma da noite para o dia, qual seria?',
  'Se ganhasse um ano sabático, o que faria primeiro?',
  'Se pudesse viver em qualquer época, qual escolheria?',
  yn('Se pudesse ler mentes por um dia, usaria?'),
  'Se ganhasse um carro dos sonhos, qual seria?',
  'Se pudesse ter um animal de estimação exótico, qual escolheria?',
  'Se acordasse famoso(a) da noite para o dia, o que faria?',
  yn('Se pudesse voltar aos 18 anos, mudaria algo?'),
  'Se ganhasse uma casa em qualquer lugar, onde seria?',
  'Se pudesse ter um talento artístico instantâneo, qual seria?',
  'Se descobrisse um portal para outro mundo, entraria?',
  yn('Se pudesse nunca mais trabalhar, o que faria?'),
  'Se ganhasse um encontro com seu eu do futuro, o que perguntaria?',
  'Se pudesse eliminar um problema mundial, qual seria?',
  yn('Se pudesse reviver um dia da sua vida, qual seria?'),
  'Se ganhasse ingressos VIP para qualquer evento, qual escolheria?',
  'Se pudesse ter uma conversa honesta com qualquer pessoa viva, quem seria?',
  'Se acordasse com R$ 1 milhão, qual seria a primeira compra?',
  yn('Se pudesse mudar uma decisão do passado, mudaria?'),
  'Se ganhasse um curso completo de qualquer área, qual faria?',
  'Se pudesse ter um dia sem consequências, o que faria?',
  'Se descobrisse que pode viajar no tempo uma vez, iria ao passado ou futuro?',
  yn('Se pudesse ter um clone para fazer tarefas chatas, aceitaria?'),
  'Se ganhasse um jantar com seu ídolo, o que pediria?',
  'Se pudesse viver em um filme ou série, qual seria?',
  'Se acordasse com a habilidade de falar com animais, o que perguntaria?',
  yn('Se pudesse apagar um erro da história, qual seria?'),
  'Se ganhasse uma biblioteca pessoal infinita, por onde começaria?',
  'Se pudesse ter um dia de fama total, como usaria?',
  'Se descobrisse um tesouro escondido, o que faria?',
  yn('Se pudesse trocar de profissão instantaneamente, qual seria?'),
  'Se ganhasse um ano em uma ilha deserta com suprimentos, aceitaria?',
  'Se pudesse ter uma conversa com seu eu de 80 anos, o que perguntaria?',
  'Se acordasse com a capacidade de voar, para onde iria primeiro?',
  yn('Se pudesse eliminar um medo, qual seria?'),
  'Se ganhasse um passe livre em todos os parques do mundo, qual visitaria primeiro?',
  'Se pudesse ter um dia repetido infinitamente, o que faria?',
  'Se descobrisse que é personagem de um livro, o que mudaria?',
  yn('Se pudesse ter um desejo realizado sem consequências, qual seria?'),
  'Se ganhasse um encontro com um cientista famoso, o que perguntaria?',
  'Se pudesse viver em qualquer clima permanentemente, qual escolheria?',
  'Se acordasse com a habilidade de curar uma doença, qual curaria?',
  yn('Se pudesse ter uma segunda chance em algo, o que seria?'),
  'Se ganhasse a oportunidade de colonizar Marte, iria?',
];
