const YND = ['Sim', 'Não', 'Depende'];
const yn = (text) => ({ text, type: 'SINGLE_CHOICE', options: YND });

export default [
  yn('Você já sentiu ciúmes de amizades do(a) parceiro(a)?'),
  'O que te ajuda a lidar com ciúmes quando aparecem?',
  yn('Você já stalkeou perfil de alguém por ciúme?'),
  'Como você diferencia ciúme de controle?',
  yn('Você se incomoda quando o(a) parceiro(a) elogia outras pessoas?'),
  'O que você faria se descobrisse uma conversa suspeita?',
  yn('Você aceitaria que o(a) parceiro(a) saísse com ex?'),
  'Como você reage quando sente que está sendo comparado(a)?',
  yn('Você já terminou por ciúmes excessivos?'),
  'O que te faz confiar mais no(a) parceiro(a)?',
  yn('Você se incomoda com amizades muito próximas do sexo oposto?'),
  'Como você lida quando o(a) parceiro(a) não responde mensagens?',
  yn('Você já sentiu ciúmes de colegas de trabalho?'),
  'O que você considera limite saudável em relação a ciúmes?',
  yn('Você compartilharia senhas por confiança ou por controle?'),
  'Como você reage quando o(a) parceiro(a) esconde o celular?',
  yn('Você se incomoda com elogios públicos a outras pessoas?'),
  'O que te faz sentir seguro(a) sobre fidelidade?',
  yn('Você aceitaria relacionamento sem exclusividade?'),
  'Como você lida com ciúmes que você mesmo(a) considera irracionais?',
  yn('Você se incomoda quando o(a) parceiro(a) dança com outras pessoas?'),
  'O que você faria se um amigo flertasse com seu(sua) parceiro(a)?',
  yn('Você já ficou com ciúmes de família do(a) parceiro(a)?'),
  'Como você reage quando o(a) parceiro(a) menciona um ex?',
  yn('Você se incomoda com fotos antigas com ex nas redes?'),
  'O que te ajuda a não transformar ciúme em acusação?',
  yn('Você aceitaria que o(a) parceiro(a) viaje sozinho(a)?'),
  'Como você lida com elogios que o(a) parceiro(a) recebe?',
  yn('Você se incomoda com pessoas que curtem todas as fotos do(a) parceiro(a)?'),
  'O que você considera sinal de desconfiança justificada?',
  yn('Você já sentiu ciúmes de hobbies ou paixões do(a) parceiro(a)?'),
  'Como você reage quando o(a) parceiro(a) tem segredos?',
  yn('Você aceitaria que o(a) parceiro(a) trabalhe com ex?'),
  'O que te faz sentir que o ciúme está saudável?',
  yn('Você se incomoda com mensagens de madrugada de desconhecidos?'),
  'Como você lida quando o(a) parceiro(a) não quer te apresentar a alguém?',
  yn('Você já sentiu ciúmes de animais de estimação?'),
  'O que você faria se o(a) parceiro(a) mentisse sobre onde estava?',
  yn('Você aceitaria que o(a) parceiro(a) tenha amizades secretas?'),
  'Como você reage quando o(a) parceiro(a) minimiza seus ciúmes?',
  yn('Você se incomoda com elogios a celebridades?'),
  'O que te faz sentir que precisa de mais transparência?',
  yn('Você aceitaria que o(a) parceiro(a) saia em grupo sem você?'),
  'Como você lida com ciúmes de conquistas profissionais do(a) parceiro(a)?',
  yn('Você se incomoda quando o(a) parceiro(a) não posta vocês?'),
  'O que você faria se descobrisse mentiras pequenas repetidas?',
  yn('Você acredita que ciúme pode ser eliminado totalmente?'),
  'Como você pediria mais segurança sem parecer controlador(a)?',
  yn('Você se incomoda quando o(a) parceiro(a) recebe convites solteiros?'),
  'O que te ajuda a distinguir ciúme de intuição?',
];
