const YND = ['Sim', 'Não', 'Depende'];
const yn = (text) => ({ text, type: 'SINGLE_CHOICE', options: YND });

export default [
  yn('Você sonha com pedido de casamento tradicional?'),
  'Como você imagina a decoração do casamento?',
  yn('Você prefere casamento no civil ou na igreja?'),
  'Qual tradição de casamento você gostaria de incluir?',
  yn('Você aceitaria casamento sem festa?'),
  'Como você imagina os votos?',
  yn('Você prefere noiva/noivo entrar sozinho(a) ou acompanhado(a)?'),
  'Qual música seria perfeita para a primeira dança?',
  yn('Você aceitaria casamento destino?'),
  'Como você imagina a lista de convidados?',
  yn('Você prefere vestido/traje clássico ou moderno?'),
  'Qual papel a família teria na cerimônia?',
  yn('Você aceitaria casamento com orçamento limitado?'),
  'Como você imagina a lua de mel?',
  yn('Você prefere cerimônia ao ar livre ou fechada?'),
  'Qual promessa você faria além dos votos tradicionais?',
  yn('Você aceitaria casamento íntimo com poucos convidados?'),
  'Como você imagina as fotos do casamento?',
  yn('Você prefere buffet ou menu fechado?'),
  'Qual tradição de outra cultura te atrai para um casamento?',
  yn('Você aceitaria casamento sem alianças?'),
  'Como você imagina o discurso dos padrinhos?',
  yn('Você prefere casamento de dia ou à noite?'),
  'Qual detalhe tornaria o casamento inesquecível?',
  yn('Você aceitaria casamento com transmissão online?'),
  'Como você imagina a despedida de solteiro(a)?',
  yn('Você prefere casamento tradicional ou alternativo?'),
  'Qual valor você quer que o casamento represente?',
  yn('Você aceitaria casamento sem pai/mãe te acompanhando?'),
  'Como você imagina a primeira semana de casados?',
  yn('Você prefere casamento com muita ou pouca decoração?'),
  'Qual tradição você criaria para o casamento?',
  yn('Você aceitaria casamento em outra cidade?'),
  'Como você imagina o bolo ou a sobremesa?',
  yn('Você prefere casamento com ou sem padrinhos?'),
  'Qual momento da cerimônia te emocionaria mais?',
  yn('Você aceitaria casamento com tema específico?'),
  'Como você imagina os convites?',
  yn('Você prefere casamento com banda ao vivo ou DJ?'),
  'Qual promessa você espera ouvir do(a) parceiro(a)?',
  yn('Você aceitaria casamento sem fotógrafo profissional?'),
  'Como você imagina a convivência pós-casamento?',
  yn('Você prefere casamento grande ou pequeno?'),
  'Qual tradição familiar você incluiria?',
  yn('Você aceitaria casamento com cerimônia simbólica?'),
  'Como você imagina celebrar aniversários de casamento?',
  yn('Você prefere aliança clássica ou personalizada?'),
  'O que o casamento significa para você emocionalmente?',
  yn('Você aceitaria casamento com cerimônia apenas simbólica?'),
  'Como você imagina lidar com conflitos sendo casados?',
];
