const YND = ['Sim', 'Não', 'Depende'];
const yn = (text) => ({ text, type: 'SINGLE_CHOICE', options: YND });

export default [
  yn('Você tem reserva de emergência?'),
  'Qual foi a compra que mais te arrependeu?',
  yn('Você negocia preços ou aceita o valor?'),
  'Como você lida com gastos inesperados?',
  yn('Você usa cartão de crédito com frequência?'),
  'Qual porcentagem da renda você gostaria de poupar?',
  yn('Você já emprestou dinheiro e se arrependeu?'),
  'Como você define "compra consciente"?',
  yn('Você acompanha seus gastos mensalmente?'),
  'Qual meta financeira te motiva mais?',
  yn('Você prefere pagar à vista ou parcelar?'),
  'Como você lida com pressão para gastar em ocasiões sociais?',
  yn('Você investe em educação financeira?'),
  'Qual hábito financeiro você quer mudar?',
  yn('Você compartilha contas com alguém?'),
  'Como você lida com diferenças de renda?',
  yn('Você tem seguro — saúde, vida ou patrimonial?'),
  'Qual gasto você considera investimento, não despesa?',
  yn('Você usa apps de controle financeiro?'),
  'Como você lida com tentações de compra impulsiva?',
  yn('Você prefere qualidade ou preço baixo?'),
  'Qual sonho financeiro você tem para os próximos cinco anos?',
  yn('Você conversa sobre dinheiro com facilidade?'),
  'Como você lida com pedidos de empréstimo de conhecidos?',
  yn('Você tem plano para aposentadoria?'),
  'Qual gasto você nunca economizaria?',
  yn('Você prefere experiências ou bens materiais?'),
  'Como você lida com inflação e custo de vida?',
  yn('Você já fez dívida por impulso?'),
  'Qual hábito financeiro você aprendeu tarde?',
  yn('Você doa dinheiro para causas?'),
  'Como você lida com presentes caros que não pode retribuir?',
  yn('Você prefere morar de aluguel ou financiar?'),
  'Qual meta financeira parece impossível hoje?',
  yn('Você tem conta conjunta com alguém?'),
  'Como você lida com gastos de saúde?',
  yn('Você prefere trabalhar mais ou gastar menos?'),
  'Qual compra te deu mais satisfação?',
  yn('Você acompanha cotações e investimentos?'),
  'Como você lida com comparar patrimônio com outras pessoas?',
  yn('Você tem limite de gastos por mês?'),
  'Qual hábito financeiro você herdou da família?',
  yn('Você prefere pagar dívidas rápido ou aos poucos?'),
  'Como você lida com gastos de lazer?',
  yn('Você tem reserva para viagens?'),
  'Qual meta financeira você alcançou e se orgulha?',
  yn('Você prefere transparência total sobre finanças?'),
  'Como você lida com gastos de filhos ou dependentes?',
  yn('Você tem plano B se perder a renda principal?'),
  'Qual conselho financeiro você daria para si mesmo(a)?',
];
