const YND = ['Sim', 'Não', 'Depende'];
const yn = (text) => ({ text, type: 'SINGLE_CHOICE', options: YND });

export default [
  yn('Você prefere ouvir antes de falar?'),
  yn('Você se considera uma pessoa intuitiva?'),
  'Como você lida com tédio?',
  yn('Você precisa de rotina para funcionar bem?'),
  yn('Você se distrai com facilidade?'),
  'O que te tira do sério mais rápido?',
  yn('Você gosta de assumir riscos calculados?'),
  'Como você reage quando alguém te interrompe?',
  yn('Você é mais perfeccionista ou pragmático(a)?'),
  'O que te faz sentir energizado(a)?',
  yn('Você guarda segredos com facilidade?'),
  'Como você se comporta em ambientes desconhecidos?',
  yn('Você se considera uma pessoa sensível?'),
  'O que te faz perder a paciência consigo mesmo(a)?',
  yn('Você prefere resolver problemas sozinho(a) ou em grupo?'),
  'Como você lida com elogios exagerados?',
  yn('Você costuma procrastinar?'),
  'O que te faz sentir inseguro(a)?',
  yn('Você se adapta bem a regras rígidas?'),
  'Como você reage quando perde um jogo ou aposta?',
  yn('Você gosta de surpresas?'),
  'O que te faz sentir realizado(a) num dia comum?',
  yn('Você se considera uma pessoa organizada?'),
  'Como você lida com silêncio prolongado?',
  yn('Você prefere profundidade ou leveza nas conversas?'),
  'O que te faz sentir pressionado(a)?',
  yn('Você se considera uma pessoa leal?'),
  'Como você reage quando alguém te corrige em público?',
  yn('Você gosta de estar no controle das situações?'),
  'O que te faz sentir culpa sem motivo aparente?',
  yn('Você se considera uma pessoa criativa?'),
  'Como você lida com incerteza?',
  yn('Você prefere trabalhar sob pressão ou com calma?'),
  'O que te faz sentir respeitado(a)?',
  yn('Você se considera uma pessoa assertiva?'),
  'Como você reage quando alguém te ignora?',
  yn('Você gosta de debates e discussões intelectuais?'),
  'O que te faz sentir entediado(a) num encontro?',
  yn('Você se considera uma pessoa grata?'),
  'Como você lida com críticas à sua aparência?',
  yn('Você prefere estabilidade ou novidade?'),
  'O que te faz sentir motivado(a) de manhã?',
  yn('Você se considera uma pessoa empática?'),
  'Como você reage quando alguém te surpreende com um presente?',
  yn('Você gosta de planejar com antecedência?'),
  'O que te faz sentir exausto(a) emocionalmente?',
  yn('Você se considera uma pessoa corajosa?'),
  'Como você lida com situações em que não tem razão?',
  yn('Você prefere dar ou receber conselhos?'),
  'O que te faz sentir orgulhoso(a) de uma escolha difícil?',
];
