const YND = ['Sim', 'Não', 'Depende'];
const yn = (text) => ({ text, type: 'SINGLE_CHOICE', options: YND });

export default [
  'O que te faz sentir desejado(a)?',
  yn('Você acredita em amor à primeira vista?'),
  'Como você sabe que está apaixonado(a)?',
  'O que te faz sentir seguro(a) num relacionamento?',
  yn('Você prefere relacionamentos intensos ou estáveis?'),
  'Qual gesto romântico te emociona de verdade?',
  'Como você lida com o fim de um relacionamento?',
  yn('Você acredita que opostos se atraem?'),
  'O que te faz sentir valorizado(a) pelo(a) parceiro(a)?',
  'Como você define compatibilidade?',
  yn('Você acredita em reconquistar um ex?'),
  'O que te faz sentir conectado(a) emocionalmente?',
  'Como você lida com diferenças de libido?',
  yn('Você prefere declarar sentimentos ou esperar?'),
  'O que te faz sentir ciúmes saudáveis?',
  'Como você imagina envelhecer ao lado de alguém?',
  yn('Você acredita em relacionamento à distância?'),
  'O que te faz sentir respeitado(a) no amor?',
  'Como você lida com períodos de rotina no relacionamento?',
  yn('Você gosta de relacionamentos públicos nas redes?'),
  'O que te faz sentir amado(a) nas pequenas coisas?',
  'Como você define intimidade emocional?',
  yn('Você acredita em segundas chances no amor?'),
  'O que te faz sentir atraído(a) além da aparência?',
  'Como você lida com diferenças de ritmo de vida?',
  yn('Você prefere namoro casual ou compromisso?'),
  'O que te faz sentir que encontrou "a pessoa certa"?',
  'Como você lida com expectativas sobre relacionamento?',
  yn('Você acredita que o amor muda com o tempo?'),
  'O que te faz sentir desconfortável num encontro romântico?',
  'Como você demonstra interesse sem ser invasivo(a)?',
  yn('Você gosta de relacionamentos com muito tempo juntos?'),
  'O que te faz sentir que o relacionamento evolui?',
  'Como você lida com diferenças de temperamento?',
  yn('Você acredita em paixão eterna?'),
  'O que te faz sentir que pode ser vulnerável?',
  'Como você lida com críticas sobre sua escolha de parceiro(a)?',
  yn('Você prefere surpresas ou previsibilidade no amor?'),
  'O que te faz sentir que o relacionamento tem futuro?',
  'Como você lida com diferenças de gostos?',
  yn('Você acredita em relacionamento aberto?'),
  'O que te faz sentir que está sendo escolhido(a)?',
  'Como você lida com momentos de dúvida no amor?',
  yn('Você gosta de relacionamentos com humor e brincadeira?'),
  'O que te faz sentir que o amor é recíproco?',
  'Como você lida com diferenças de ambição?',
  yn('Você acredita que o amor supera tudo?'),
  'O que te faz sentir que pode construir algo junto?',
  yn('Você gosta de relacionamentos com metas compartilhadas?'),
  'Como você lida quando o romance esfria por um tempo?',
];
