const YND = ['Sim', 'Não', 'Depende'];
const yn = (text) => ({ text, type: 'SINGLE_CHOICE', options: YND });

export default [
  yn('Você usa redes sociais todo dia?'),
  'Qual rede você usaria se tivesse que escolher só uma?',
  yn('Você posta stories com frequência?'),
  'Como você lida com haters ou comentários negativos?',
  yn('Você curte posts de ex ou antigos contatos?'),
  'Qual conteúdo você nunca postaria?',
  yn('Você usa filtros em todas as fotos?'),
  'Como você lida com FOMO nas redes?',
  yn('Você segue influenciadores ou creators?'),
  'Qual rede te consome mais tempo?',
  yn('Você apaga posts antigos?'),
  'Como você lida com comparação de corpo nas redes?',
  yn('Você usa redes para trabalho?'),
  'Qual limite de tempo de tela você impõe?',
  yn('Você posta fotos sem maquiagem ou filtro?'),
  'Como você lida com viralização inesperada?',
  yn('Você usa LinkedIn ou redes profissionais?'),
  'Qual rede você considera mais tóxica?',
  yn('Você responde DMs de desconhecidos?'),
  'Como você lida com cancelamentos online?',
  yn('Você posta opiniões políticas?'),
  'Qual rede te traz mais alegria?',
  yn('Você usa modo escuro?'),
  'Como você lida com notificações constantes?',
  yn('Você posta fotos de comida?'),
  'Qual rede você abandonou e por quê?',
  yn('Você usa redes para namoro ou conhecer pessoas?'),
  'Como você lida com privacidade online?',
  yn('Você posta viagens em tempo real?'),
  'Qual rede te deixa mais ansioso(a)?',
  yn('Você usa redes no banheiro ou na cama?'),
  'Como você lida com algoritmos e recomendações?',
  yn('Você posta selfies com frequência?'),
  'Qual rede você usa para notícias?',
  yn('Você bloqueia ou silencia contas?'),
  'Como você lida com exposição de filhos ou família?',
  yn('Você posta conteúdo educativo?'),
  'Qual rede te conecta com amigos distantes?',
  yn('Você usa redes durante refeições?'),
  'Como você lida com desinformação?',
  yn('Você posta memes ou humor?'),
  'Qual rede você considera essencial hoje?',
  yn('Você usa redes para vender ou empreender?'),
  'Como você lida com dependência de likes?',
  yn('Você posta rotina de exercícios?'),
  'Qual rede você esconderia de certas pessoas?',
  yn('Você usa redes para aprender algo?'),
  'Como você lida com exposição do relacionamento?',
  yn('Você faria detox de redes por uma semana?'),
  'O que te faria deletar todas as redes?',
];
