const YND = ['Sim', 'Não', 'Depende'];
const yn = (text) => ({ text, type: 'SINGLE_CHOICE', options: YND });

export default [
  yn('Você acredita em karma ou lei do retorno?'),
  'Como a espiritualidade te ajuda em momentos difíceis?',
  yn('Você pratica alguma religião ativamente?'),
  'Qual ritual te traz paz?',
  yn('Você acredita em anjos ou proteção espiritual?'),
  'Como você lida com dúvidas sobre fé?',
  yn('Você frequenta templos, igrejas ou centros espirituais?'),
  'Qual ensinamento espiritual te marcou?',
  yn('Você acredita em reencarnação?'),
  'Como você define "milagre"?',
  yn('Você ora ou reza com frequência?'),
  'Qual prática espiritual você gostaria de experimentar?',
  yn('Você acredita que tudo acontece por um motivo?'),
  'Como você lida com pessoas de fé diferente?',
  yn('Você lê textos sagrados ou espirituais?'),
  'Qual momento te fez questionar a fé?',
  yn('Você acredita em energia ou vibração?'),
  'Como a espiritualidade aparece nas suas escolhas?',
  yn('Você participa de retiros ou eventos espirituais?'),
  'Qual valor espiritual guia sua vida?',
  yn('Você acredita em destino ou livre-arbítrio?'),
  'Como você lida com luto do ponto de vista espiritual?',
  yn('Você medita regularmente?'),
  'Qual tradição espiritual te atrai?',
  yn('Você acredita em premonições ou sinais?'),
  'Como você ensinaria espiritualidade para uma criança?',
  yn('Você acredita em vida após a morte?'),
  'Qual prática te conecta com algo maior?',
  yn('Você evita falar de religião em conversas?'),
  'Como você lida com críticas à sua fé?',
  yn('Você acredita em cura espiritual?'),
  'Qual momento de silêncio te fez sentir presença divina?',
  yn('Você usa amuletos ou símbolos de proteção?'),
  'Como você define "propósito de vida"?',
  yn('Você acredita em oração coletiva?'),
  'Qual festa religiosa ou espiritual você mais valoriza?',
  yn('Você busca respostas em astrologia ou tarô?'),
  'Como você lida com incerteza sobre o futuro?',
  yn('Você acredita em perdão espiritual?'),
  'Qual lição espiritual você aprendeu com um erro?',
  yn('Você pratica gratidão como ritual?'),
  'Como você honra quem partiu?',
  yn('Você acredita em proteção de antepassados?'),
  'Qual prática espiritual você abandonou e por quê?',
  yn('Você sente que a fé te limita ou liberta?'),
  'Como você define "fé" para si?',
  yn('Você acredita que o universo conspira a seu favor?'),
  'O que te dá esperança quando tudo parece difícil?',
  yn('Você acredita que coincidências significativas existem?'),
  'Como você lida com momentos em que a fé parece distante?',
];
