const YND = ['Sim', 'Não', 'Depende'];
const yn = (text) => ({ text, type: 'SINGLE_CHOICE', options: YND });

export default [
  'O que você faria se visse alguém sendo discriminado?',
  yn('Você defenderia um amigo mesmo tendo razão o outro?'),
  'Qual valor você herdou dos seus pais?',
  yn('Você mudaria de emprego por ética?'),
  'O que te faz perder a admiração por alguém?',
  yn('Você doaria um rim para um desconhecido?'),
  'Como você define "justiça"?',
  yn('Você mentiria para proteger alguém?'),
  'Qual causa você apoiaria com tempo e dinheiro?',
  yn('Você boicotaria uma marca por valores?'),
  'O que te faz sentir orgulho moral?',
  yn('Você denunciaria um crime mesmo com risco?'),
  'Como você lida com dilemas éticos no trabalho?',
  yn('Você perdoaria uma traição de confiança?'),
  'Qual valor você ensinaria em uma escola?',
  yn('Você aceitaria suborno em situação extrema?'),
  'O que te faz sentir que agiu corretamente?',
  yn('Você defenderia um estranho injustiçado?'),
  'Como você define "coragem moral"?',
  yn('Você quebraria uma regra por compaixão?'),
  'Qual valor você nunca negociaria?',
  yn('Você contaria a verdade que machuca?'),
  'O que te faz sentir que alguém tem caráter?',
  yn('Você apoiaria um amigo em decisão errada?'),
  'Como você lida com hipocrisia?',
  yn('Você doaria anonimamente?'),
  'Qual valor te guia em relacionamentos?',
  yn('Você aceitaria emprego em empresa controversa?'),
  'O que te faz sentir que fez a coisa certa?',
  yn('Você perdoaria quem te prejudicou financeiramente?'),
  'Como você define "empatia" na prática?',
  yn('Você denunciaria um colega desonesto?'),
  'Qual valor você mais admira em líderes?',
  yn('Você mentiria em currículo?'),
  'O que te faz sentir que alguém é íntegro?',
  yn('Você apoiaria protesto pacífico?'),
  'Como você lida com valores conflitantes?',
  yn('Você aceitaria ganhar menos por ética?'),
  'Qual valor você quer deixar como legado?',
  yn('Você contaria segredo que prometeu guardar?'),
  'O que te faz sentir que agiu por medo?',
  yn('Você defenderia animal maltratado?'),
  'Como você define "honra"?',
  yn('Você aceitaria vantagem injusta?'),
  'Qual valor te guia em decisões financeiras?',
  yn('Você perdoaria quem mentiu para você?'),
  'O que te faz sentir que alguém é confiável?',
  yn('Você apoiaria amigo em divórcio polêmico?'),
  'Como você lida com valores da sociedade vs. seus?',
  yn('Você faria sacrifício grande por um valor?'),
];
